apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system: masters
      rolearn: arn:aws:iam::952262784007:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C37C192GHY3I
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-23T10:37:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1640"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d248e3f7-c7fe-4a42-b356-1347657176c5
