apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::952262784007:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::952262784007:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1491Q5XXG6Y03
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-24T18:38:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2762"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a65e68a7-a7f7-4aa0-bbb7-5f3c6e790154
