apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::952262784007:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1HA1UPWPHFM9V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::952262784007:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-24T11:59:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1573"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 53676997-a973-4b54-894c-aee0e01f30ee
